export const GET_LEAVE_PENDING  = "GET_LEAVE_PENDING";
export const GET_LEAVE_PENDING_SUCCESS = "GET_LEAVE_PENDING_SUCCESS";
export const GET_LEAVE_PENDING_FAILURE = "GET_LEAVE_PENDING_FAILURE";

export const CREATE_LEAVE_REQUEST  = "CREATE_LEAVE_REQUEST";
export const CREATE_LEAVE_REQUEST_SUCCESS = "CREATE_LEAVE_REQUEST_SUCCESS";
export const CREATE_LEAVE_REQUEST_FAILURE = "CREATE_LEAVE_REQUEST_FAILURE";
export const CREATE_LEAVE_REQUEST_CLEAR = "CREATE_LEAVE_REQUEST_CLEAR";

export const UPDATE_LEAVE_REQUEST  = "UPDATE_LEAVE_REQUEST";
export const UPDATE_LEAVE_REQUEST_SUCCESS = "UPDATE_LEAVE_REQUEST_SUCCESS";
export const UPDATE_LEAVE_REQUEST_FAILURE = "UPDATE_LEAVE_REQUEST_FAILURE";
export const UPDATE_LEAVE_REQUEST_CLEAR = "UPDATE_LEAVE_REQUEST_CLEAR";

export const CREATE_PREMISSION_REQUEST  = "CREATE_PREMISSION_REQUEST";
export const CREATE_PREMISSION_REQUEST_SUCCESS = "CREATE_PREMISSION_REQUEST_SUCCESS";
export const CREATE_PREMISSION_REQUEST_FAILURE = "CREATE_PREMISSION_REQUEST_FAILURE";
export const CREATE_PREMISSION_REQUEST_CLEAR = "CREATE_PREMISSION_REQUEST_CLEAR";