export const LOGIN  = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTERATION  = "REGISTERATION";
export const REGISTERATION_SUCCESS = "REGISTERATION_SUCCESS";
export const REGISTERATION_FAILURE = "REGISTERATION_FAILURE";

export const VALID_SESSION  = "VALID_SESSION";